version: '3.8'
services:
  dev-db:
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      - MONGO_INITDB_DATABASE=dev
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    networks:
      - nestjs-net

  test-db:
    build: ./mongodb_replica
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27018
    ports:
      - 27018:27018
    networks:
      - nestjs-net
networks:
  nestjs-net:
